version: "3.1"
services:
    #redis:
    #    image: 'redis:alpine'

    # mysql:
    #    image: 'mysql:8.0'
    #    working_dir: /application
    #    volumes:
    #        - '.:/application'
    #    environment:
    #        - MYSQL_ROOT_PASSWORD=rootuserpwd
    #        - MYSQL_DATABASE=test-app
    #        - MYSQL_USER=test-app-user
    #        - MYSQL_PASSWORD=test-apppwd
    #    ports:
    #        - '58002:3306'

    app:
        build:
            dockerfile: ./Dockerfile
        container_name: laravel-docker-app
        working_dir: /var/www
        restart: unless-stopped
        tty: true
        volumes:
            - ./:/var/www

    webserver:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        volumes:
            - ./:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/logs:/var/log/nginx
        ports:
            - "80:80"
            - "8000:8000"
            - "443:443"
        expose:
            - "80"
            - "443"

    php-fpm:
        image: php:8.2.12-fpm
        restart: unless-stopped
        tty: true
        volumes:
            - ./:/var/www
            - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/app.ini
            - ./docker/php-fpm/logs:/var/log/php
